spring:
  application:
    name: user-service
server:
    port: 8081
zuul:
  routes:
    images:
      path: /images/**
      url: http://localhost:8082/file/getfile/
    receipes:
      path: /receipes/**
      url: http://localhost:8083/v1/Receipe/