spring:
  application:
    name: user-service
server.ip: 
 92.53.91.47
server.port: 
  8008
idp:
  url: localhost:8181
ui:
  url: ${server.ip}:${server.port}    
security:
    basic:
        enabled: false  
service:
    id: ui
    secret: uipass
zuul:
    routes:
        images:
            path: /images/**
            url: http://localhost:8082/file/getfile/
        receipes:
            path: /receipes/**
            url: http://localhost:8083/v1/Receipe
