spring:
  application:
    name: user-service
idp:
  url: localhost:8181
server:
    port: 8081
security:
  basic:
    enabled: false
service:
  id: ui
  secret: uipass
zuul:
  routes:
    images:
      path: /file/getfile/**
      url: http://localhost:8082/file/getfile/
     # receipes:
     # path: /receipes/**
     # url: http://localhost:8083/v1/Receipe
